framework:
    messenger:
        default_bus: messenger.bus.default
        transports:
            async:
                dsn: 'amqp://%env(RABBITMQ_USER)%:%env(RABBITMQ_PASS)%@%env(RABBITMQ_HOST)%:%env(RABBITMQ_PORT)%/%env(resolve:RABBITMQ_VHOST)%'
                options:
                    exchange:
                        name: notifications
                        type: direct
                        default_publish_routing_key: notifications
                    queues:
                        notifications:
                            binding_keys: ['notifications']
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
            failed:
                dsn: 'doctrine://default?queue_name=failed'
        failure_transport: failed
        routing:
            App\Notification\Application\Command\SendNotificationCommand: async
